Update pre-exit

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -1,34 +1,33 @@
 #!/usr/bin/env bash
 
-set -eo pipefail
+set -euo pipefail
 
-if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" \
-    || "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_DELETE_CHECKOUT" != "true" ]]; then
+# Functions
+
+log_info() {
+  echo -e "INFO: $1"
+}
+
+log_error() {
+  echo -e "ERROR: $1" >&2
+}
+
+# Main Execution
+
+if [[ "${BUILDKITE_PLUGIN_IMPROVED_CHECKOUT_DELETE_CHECKOUT:-false}" != "true" ]]; then
   exit 0
 fi
 
-echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
-# redirecting rm's stderr to /dev/null
-# because it would pollute the logs if there were a lot of files inside the folder to be removed.
-# Example: `node_modules` folder created by a different user in a container during a build throwing
-# permission error for each of the files inside it.
-rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
-  echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
-  echo "But it failed leaving the following files as residue"
-  ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
-}
+log_info "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
 
-if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Attempting to cleanup with sudo"
-  sudo -n rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" || {
-    echo "Tried running: sudo -n rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
-    echo "But it failed leaving the following files as residue"
-    ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
-  }
-fi
-
-if [ ! -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Cleanup completed successfully."
+if rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"; then
+  log_info "Checkout directory removed successfully."
 else
-  echo "Cleanup was not successful."
+  log_error "Failed to remove checkout directory. Attempting with sudo."
+  if sudo rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"; then
+    log_info "Checkout directory removed successfully with sudo."
+  else
+    log_error "Failed to remove checkout directory even with sudo."
+    ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
+  fi
 fi
