Update pre-exit

diff --git a/hooks/pre-exit b/hooks/pre-exit
--- a/hooks/pre-exit
+++ b/hooks/pre-exit
@@ -2,33 +2,51 @@
 
 set -eo pipefail
 
-if [[ "$BUILDKITE_PLUGIN_CUSTOM_CHECKOUT_SKIP_CHECKOUT" == "true" \
-    || "$BUILDKITE_PLUGIN_CUSTOM_CHECKOUT_DELETE_CHECKOUT" != "true" ]]; then
-  exit 0
-fi
-
-echo "Removing checkout directory: $BUILDKITE_BUILD_CHECKOUT_PATH"
-# redirecting rm's stderr to /dev/null
-# because it would pollute the logs if there were a lot of files inside the folder to be removed.
-# Example: `node_modules` folder created by a different user in a container during a build throwing
-# permission error for each of the files inside it.
-rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" 2>/dev/null || {
-  echo "Tried running: rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
-  echo "But it failed leaving the following files as residue"
-  ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
+function log_info {
+  echo "$1"
 }
 
-if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Attempting to cleanup with sudo"
-  sudo -n rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH" || {
-    echo "Tried running: sudo -n rm -rf $BUILDKITE_BUILD_CHECKOUT_PATH"
-    echo "But it failed leaving the following files as residue"
-    ls -la "$BUILDKITE_BUILD_CHECKOUT_PATH"
-  }
-fi
+function log_error {
+  echo "$1"
+}
 
-if [ ! -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
-  echo "Cleanup completed successfully."
-else
-  echo "Cleanup was not successful."
-fi
+function remove_directory {
+  local dir=$1
+  rm -rf "$dir" 2>/dev/null || {
+    log_error "Tried running: rm -rf $dir"
+    log_error "But it failed leaving the following files as residue"
+    ls -la "$dir"
+  }
+}
+
+function remove_directory_with_sudo {
+  local dir=$1
+  sudo -n rm -rf "$dir" || {
+    log_error "Tried running: sudo -n rm -rf $dir"
+    log_error "But it failed leaving the following files as residue"
+    ls -la "$dir"
+  }
+}
+
+function cleanup_checkout_directory {
+  local dir=$1
+  if [[ "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_SKIP_CHECKOUT" == "true" || "$BUILDKITE_PLUGIN_SMOOTH_CHECKOUT_DELETE_CHECKOUT" != "true" ]]; then
+    exit 0
+  fi
+
+  log_info "Removing checkout directory: $dir"
+  remove_directory "$dir"
+
+  if [ -d "$dir" ]; then
+    log_info "Attempting to cleanup with sudo"
+    remove_directory_with_sudo "$dir"
+  fi
+
+  if [ ! -d "$dir" ]; then
+    log_info "Cleanup completed successfully."
+  else
+    log_error "Cleanup was not successful."
+  fi
+}
+
+cleanup_checkout_directory "$BUILDKITE_BUILD_CHECKOUT_PATH"
